### ISSUE TITLE
Be able to save and use variables

### ISSUE THREAD

**Issue by Hedronmx** [CleoMenezesJr/escambo#36]
Would be nice to set up global variables to save and use! 

I really love this application! Just donated to your kofi, enjoy your coffee haha!

**Comment by CleoMenezesJr** [comment]
Hey. First, thank you!! It's great to know that the app is so useful for you that you wanted to contribute with a coffee. That's great.

I'm sorry, but you're late. haha
I already opened an issue (#34) about it, and I'm already working on this feature.
In a few weeks it should already be available for download.
