### ISSUE TITLE
Authentication x Authorization mixup 

### ISSUE THREAD

**Issue by rffontenelle** [CleoMenezesJr/escambo#44]
"auths" gschemas has description "Authentication", and it affects Authorization toggle in the headerbar's Authorization item.

Authentication and authorization are different concepts: Authentication says who are you, while authorization says what you have permission to do. "Auth" may refer to one, other or both.

Not sure which one is correct in this particular case, though.

![Captura de tela de 2023-05-19 22-47-14](https://github.com/CleoMenezesJr/escambo/assets/1571783/3a8dd39d-da13-4546-ba5b-d33718939d67)

**Comment by CleoMenezesJr** [comment]
The correct one should be Authorization. "Authentication" is a problem that has survived historical changes. haha
Thanks, I didn't realize this problem still existed.
